INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("PROTEIN","1lb Chicken Breast", 135.5, "false", 20, 20, 1.50, 5.00, "Animal", "false", "true", "false");
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("PROTEIN","1lb Ground Beef", 150, "false", 20, 50, 1.25, 5.50, "Animal", "false", "true", "false");
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("PROTEIN","1lb Salmon Fillet", 120, "false", 15, 20, 2.50, 7.00, "Seafood", "false", "true", "false");
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("PROTEIN","1lb Bacon", 200, "false", 20, 20, 1.50, 5.00, "Animal", "false", "true", "false");
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("PROTEIN","Silken Tofu", 100, "false", 18, 20, 2.50, 6.00, "Soy", "true", "true", "true");


INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("VEGETABLE","Lettuce", 25, "false", 20, 30, 1.00, 3.00, "true",null, null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("VEGETABLE","Green Bean", 55, "false", 25, 40, 1.50, 4.00, "true",null, null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("VEGETABLE","Tomato", 35, "false", 20, 30, 1.00, 3.00, "true",null, null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("VEGETABLE","Potato", 105, "false", 50, 70, 1.00, 4.00, "true",null, null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("VEGETABLE","Brussel Sprouts", 65, "false", 20, 30, 3.00, 6.00, "false",null, null, null);


INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("FRUIT","Apple", 55, "false", 40, 100, 1.25, 2.25, "true",null, null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("FRUIT","Orange", 35, "false", 40, 50, 1.25, 4.25, "false",null, null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("FRUIT","Banana", 45, "false", 40, 70, 1.25, 2.25, "false",null, null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("FRUIT","Pear", 55, "false", 20, 30, 1.25, 3.25, "false",null, null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("FRUIT","Fig", 65, "false", 45, 50, 1.25, 5.25, "false",null, null, null);

INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("GRAIN","White Rice", 50, "false", 100, 150, 1.50, 3.50, "true", "false",null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("GRAIN","Bread", 100, "false", 100, 150, 2.50, 5.00, "false", "false",null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("GRAIN","Brown Rice", 40, "false", 100, 150, 1.50, 5.50, "true", "true",null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("GRAIN","Farro", 45, "false", 100, 150, 2.50, 4.00, "true", "false",null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("GRAIN","Steel Cut Oates", 20, "false", 100, 150, 1.25, 4.00, "true", "false",null, null);

INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("DAIRY","Cow Milk", 200, "true", 200, 250, 2.25, 4.50, "Cow", "true",null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("DAIRY","Goat Milk", 180, "true", 50, 60, 3.25, 7.50, "Goat", "true",null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("DAIRY","Almond Milk", 125, "true", 200, 250, 4.25, 8.50, "Almond", "false",null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("DAIRY","Swiss Cheese", 200, "true", 200, 250, 1.25, 4.50, "Cow", "true",null, null);
INSERT INTO FOOD_ITEM (FOOD_TYPE, NAME, CALORIES, IS_RELATED_TO_FOOD_ALLERGY, QUANTITY, MAX_QUANTITY, WHOLESALE_COST, RETAIL_PRICE, CUSTOM_FIELD1, CUSTOM_FIELD2, CUSTOM_FIELD3, CUSTOM_FIELD4) 
VALUES ("DAIRY","Yogurt", 100, "true", 200, 250, 1.25, 4.50, "Cow", "true",null, null);